USE [master]
GO
CREATE DATABASE [TestAssignmentFileParser]
GO
USE [TestAssignmentFileParser]
GO
CREATE TABLE [dbo].[File](
 [Id] [int] IDENTITY(1,1) NOT NULL,
 [FolderId] [int] NOT NULL,
 [Name] [nvarchar](400) NOT NULL,
 [Path] [nvarchar](400) NOT NULL,
 CONSTRAINT [PK_File] PRIMARY KEY CLUSTERED 
(
 [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE TABLE [dbo].[Folder](
 [Id] [int] IDENTITY(1,1) NOT NULL,
 [Folder] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Folder] PRIMARY KEY CLUSTERED 
(
 [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE TABLE [dbo].[Word](
 [Id] [int] IDENTITY(1,1) NOT NULL,
 [FileId] [int] NOT NULL,
 [Word] [nvarchar](500) NOT NULL,
 [ColumnNumber] [int] NOT NULL,
 [ColumnRow] [int] NOT NULL,
 CONSTRAINT [PK_Word] PRIMARY KEY CLUSTERED 
(
 [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_Folder_ID] ON [dbo].[File]
(
 [FolderId] ASC
)
INCLUDE (  [Id],
 [Name],
 [Path]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IDX_File_ID] ON [dbo].[Word]
(
 [FileId] ASC
)
INCLUDE (  [Word],
 [ColumnNumber],
 [ColumnRow]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[File]  ADD  CONSTRAINT [FK_File_Folder] FOREIGN KEY([FolderId])
REFERENCES [dbo].[Folder] ([Id])
GO
ALTER TABLE [dbo].[Word]  ADD  CONSTRAINT [FK_Word_File] FOREIGN KEY([FileId])
REFERENCES [dbo].[File] ([Id])
GO